# Site setting
title: Hopp
description: There's still hope. Probably.
plugins:
  - jekyll-relative-links

# Theme
remote_theme: pmarsceill/just-the-docs

# Theme settings
# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Enable or disable the site search
# Use this command to update index: bundle exec just-the-docs rake search:init
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Footer content appears at the bottom of every page's main content
footer_content: "There's still hope. Probably."

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/oktavilla/hopp-docs"

relative_links:
  enabled:     true
  collections: true
