- field: "Key"
  required: "Yes"

- field: "Title"
  required: "Yes"

- field: "URL"
  required: "Yes"

- field: "Icon reference"
  required: "No"

- field: "Parent"
  required: "No"
  comment: "A key to another menu item"
