- field: "Product Name"
  required: "Yes"
 
- field: "Content Item Lists Layout"
  required: "Yes"
  comment: "Defines how content item lists are displayed generally throughout the product. Either \"grid\" or \"list\""

- field: "Site Language"
  required: "Yes"
  reference: "content-language"

- field: "Content Languages"
  required: "Yes"
  reference: "content-language"
  reference_type: "many"
  comment: "The first (or only) Content Language defined will be used as the default"

- field: "Facebook App ID"
  required: "Yes"
  comment: "Account used for social sharing"

- field: "Cookie information url"
  required: "Yes"
  comment: "Link to page where end user can find information about cookies"

- field: "Footer Information"
  required: "No"
  comment: "A text shown in the footer"

- field: "Content Paywall"
  required: "Yes"
  comment: "Either 'disabled', 'free_model' or 'premium_model'"

- field: "Subscription Product Identifier"
  required: "No"
  comment: "A key that corresponds to a product that allows 'access to digital premium content' in Hopp Identity"
