- field: "Contributors Top"
  required: "Yes"
  field_type: "boolean"
  comment: "Should contributors be shown in top of content items?"
- field: "Contributor In Opinion Piece Heading"
  required: "Yes"
  field_type: "boolean"
  comment: "Should title in opinion piece heading be prepended by the contributor? Only applicable when there is 1 contributor."
- field: "Show Timestamp"
  required: "Yes"
  field_type: "boolean"
- field: "Date Format"
  required: "Yes"
  comment: "Format date according to the directives in the given format string. Strftime format, e.g. \"%B %d, %Y\"."
