- field: "Template"
  required: "Yes"
  comment: "The Information Design Template to use for this Container."

- field: "List"
  required: "Yes"
  comment: "A reference to Curated Content List or Predefined List."

- field: "Header"
  required: "No"
  field_type: "object"
  comment: "Container Header object. See separate definition."

- field: "Preferences"
  required: "No"
  field_type: "object"
  comment: "A Preferences Object. Will be sent to the container template."

- field: "Grid Preferences"
  required: "No"
  field_type: "object"
  comment: "A Preferences Object. Will be sent to the container grid."

- field: "Item Preferences"
  required: "No"
  field_type: "object"
  comment: "A Preferences Object. Will affect items in the template."

- field: "Offset"
  required: "No"
  field_type: "integer"
  comment: "Start offset in list."

- field: "Number"
  required: "No"
  field_type: "integer"
  comment: "How many items should be shown from the list."
