- field: "Address type/name"
  required: "No"

- field: "Recipient"
  required: "No"

- field: "Street address"
  required: "No"

- field: "Post Office Box Number"
  required: "No"

- field: "Postal Code"
  required: "No"

- field: "Address Locality"
  required: "No"

- field: "E-mail"
  required: "No"

- field: "Telephone"
  required: "No"
