- field: "Byline Type"
  required: "No"
  comment: "either \"name\" or \"avatar_and_name\""
- field: "Show Timestamp"
  required: "Yes"
  field_type: "boolean"
- field: "Show Excerpt"
  required: "Yes"
  field_type: "boolean"
- field: "Media Position"
  required: "Yes"
  comment: "Where should teaser media be rendered? Either \"left\" or \"right\"."
- field: "Context Label Position"
  required: "Yes"
  comment: "Where should the context label be rendered? Either \"above_heading\" or \"below_heading\"."
