- field: "Template"
  required: "Yes"
  comment: "The Information Design Template to use for this Container."

- field: "Positions"
  required: "No"
  field_type: "array"
  comment: "An array of positions. See separate definition."

- field: "Content List"
  required: "No"
  comment: "A reference to a type of dynamic content list. See separate definition."

- field: "Header"
  required: "No"
  field_type: "object"
  comment: "Container Header object. See separate definition."

- field: "Preferences"
  required: "No"
  field_type: "object"
  comment: "A Preferences Object. Will be sent to the container template."

- field: "Grid Preferences"
  required: "No"
  field_type: "object"
  comment: "A Preferences Object. Will be sent to the container grid."

- field: "Item Preferences"
  required: "No"
  field_type: "object"
  comment: "A Preferences Object. Will affect items in the template."
