- field: "Show timestamps"
  required: "No"
  field_type: "boolean"
  comment: "Should timestamps be shown on Teasers and Content Item Pages? Default is true."

- field: "Show Contributors in Teasers"
  required: "No"
  field_type: "boolean"
  comment: "Should bylines be shown in teasers? Default is false."
