- field: "Category"
  required: "Yes"
  reference: "category"
  comment: "Category that should have a filter UI on its Category page"

- field: "Tag Groups"
  required: "Yes"
  reference: "tag-group"
  reference_type: "many"
  comment: "An ordered list of Tag Groups used to determine what tags should be shown as filter options"
