- field: "Page Position"
  required: "Yes"
  field_type: "page-position"
  comment: "Page position for this Service Teaser."

- field: "Render"
  required: "Yes"
  field_type: "boolean"
  comment: "Turns rendering the position on or off."

- field: "Render Only On"
  required: "No"
  reference_type: "many"
  field_type: "page-type"
  comment: "Only meaningful on positions that exist on multiple page types."

- field: "Service Teaser"
  required: "Yes"
  comment: "Identifier for the Service Teaser to render at this position."
