- field: "Page Position"
  required: "Yes"
  field_type: "page-position"
  comment: "Page position for this Ad."

- field: "Render"
  required: "Yes"
  field_type: "boolean"
  comment: "Turns rendering the position on or off."

- field: "Ad Unit Path"
  required: "Yes"
  comment: "I.e /21636186344/lo_ka_panorama_1"

- field: "Format"
  required: "No"
  comment: "One of the predefined formats for ads; currently one of \"panorama\" or \"module\". Required for Page Positions that have been added in a Curated Content layout."
