- field: "Identifier"
  required: "Yes"

- field: "Name"
  required: "Yes"

- field: "Approximate Break Off Limit"
  field_type: "integer"
  required: "Yes"
  comment: "A hint as to approximately how many teasers will be presented (at most)"

- field: "Automation Rules"
  required: "No"
  field_type: automation-rules
  comment: "References a set of rules for content selection"
